# ...

mysql: # MySQL 配置
  host: 127.0.0.1 # 服务器地址
  port: "3306" # 端口
  config: charset=utf8mb4&parseTime=True&loc=Local # 其他配置
  db_name: zyd # 数据库名称
  username: root # 数据库用户名
  password: "root" # 数据库密码
  prefix: "" # 全局表前缀，单独定义 TableName 则不生效
  singular: false # 是否开启全局禁用复数，true表示不开启
  engine: "" # 引擎，默认InnoDB
  max_idle_conns: 10 # 最大空闲连接数
  max_open_conns: 100 # 最大连接数
  log_mode: error # 日志级别
  log_zap: false # 是否通过zap写日志文件
